
const SUPABASE_URL='https://ksrxcjspnhhukqacnnvw.supabase.co';
const SUPABASE_KEY='sb_publishable_EYWjEEyYds-HPQ07z5jg0w_9hi0qEn2';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const app=document.getElementById('app'),toastEl=document.getElementById('toast');
let active='events',currentUser=null,currentRole='staff';

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=d=>d?new Date(d).toLocaleString():'—';
const slugify=s=>String(s||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const tags=v=>String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
const q=v=>'"'+String(v??'').replace(/"/g,'""')+'"';
function toast(m){toastEl.textContent=m;toastEl.style.display='block';clearTimeout(window.__toastTimer);window.__toastTimer=setTimeout(()=>toastEl.style.display='none',3200)}
function busy(btn,on,label){btn.disabled=on;btn.innerHTML=on?'<span class="spinner"></span>'+label:label}
function parseExtra(r){return r&&typeof r.extra_data==='object'&&r.extra_data?r.extra_data:{}}
function downloadCsv(rows,name='nexus-export.csv',preferred=[]){
  const keys=[...new Set([...preferred,...rows.flatMap(r=>Object.keys(r||{})),...rows.flatMap(r=>Object.keys(parseExtra(r)))])].filter(k=>k!=='extra_data');
  const label=k=>k.split('_').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');
  const lines=[keys.map(label),...rows.map(r=>keys.map(k=>parseExtra(r)[k]??r[k]??''))].map(row=>row.map(q).join(',')).join('\n');
  const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)
}
async function currentMember(){
  const {data:{session}}=await sb.auth.getSession(); if(!session?.user)return null;
  const {data,error}=await sb.from('admin_users').select('user_id,role,active').eq('user_id',session.user.id).maybeSingle();
  if(error||!data?.active)return false;
  session.user.nexusRole=data.role||'staff';return session.user
}
function pwWrap(id,name,autocomplete='current-password'){return '<div class="pw"><input id="'+id+'" type="password" name="'+name+'" autocomplete="'+autocomplete+'" required><button type="button" data-toggle="'+id+'">Show</button></div>'}
function bindPw(){document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=()=>{const i=document.getElementById(b.dataset.toggle),show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'Hide':'Show'})}
async function loginPage(){
  app.innerHTML='<div class="login"><h1>NEXUS Admin</h1><p class="lead">Authorized access for the NEXUS management team.</p><form id="loginForm" class="formgrid"><div class="field full"><label>Email</label><input id="loginEmail" type="email" autocomplete="email" required></div><div class="field full"><label>Password</label>'+pwWrap('loginPassword','password')+'</div><div id="loginStatus" class="field full muted" aria-live="polite"></div><div class="field full"><div class="authrow"><button id="loginBtn" class="btn">Sign in</button><button id="forgotBtn" class="linkbtn" type="button">Forgot password?</button></div></div></form></div>';bindPw();
  forgotBtn.onclick=async()=>{const email=loginEmail.value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){loginStatus.textContent='Enter a valid email address first.';return}forgotBtn.disabled=true;forgotBtn.textContent='Sending…';const {data,error}=await sb.functions.invoke('admin-recovery',{body:{email}});forgotBtn.disabled=false;forgotBtn.textContent='Forgot password?';loginStatus.textContent=error?'Unable to request a reset right now.':(data?.message||'If this account is authorized, a reset email will arrive shortly.')};
  loginForm.onsubmit=async e=>{e.preventDefault();busy(loginBtn,true,'Signing in…');loginStatus.textContent='Checking credentials…';const {error}=await sb.auth.signInWithPassword({email:loginEmail.value.trim(),password:loginPassword.value});if(error){busy(loginBtn,false,'Sign in');loginStatus.textContent='Email or password is incorrect.';return}const u=await currentMember();if(!u){await sb.auth.signOut();busy(loginBtn,false,'Sign in');loginStatus.textContent='This account does not have active NEXUS access.';return}history.replaceState({},'','/admin');shell(u)}
}
async function resetPage(){
  app.innerHTML='<div class="login"><h1>Reset password</h1><p class="lead">Choose a new password for your NEXUS account.</p><div id="resetNotice" class="notice">Verifying secure recovery link…</div><form id="resetForm" class="formgrid hidden"><div class="field full"><label>New password</label>'+pwWrap('newPassword','new_password','new-password')+'</div><div class="field full"><label>Confirm password</label>'+pwWrap('confirmPassword','confirm_password','new-password')+'</div><div id="resetStatus" class="field full muted"></div><div class="field full"><button id="resetBtn" class="btn">Update password</button></div></form></div>';bindPw();
  let shown=false;const reveal=()=>{if(shown)return;shown=true;resetNotice.textContent='Link verified.';resetForm.classList.remove('hidden')};
  const {data:{session}}=await sb.auth.getSession();if(session)reveal();
  sb.auth.onAuthStateChange((event,s)=>{if(s&&(event==='PASSWORD_RECOVERY'||event==='SIGNED_IN'||event==='INITIAL_SESSION'))reveal()});
  setTimeout(async()=>{const {data:{session:s}}=await sb.auth.getSession();if(!s&&!shown)resetNotice.innerHTML='This link is invalid or expired. <a href="/admin-login">Request a new reset email.</a>'},1600);
  resetForm.onsubmit=async e=>{e.preventDefault();if(newPassword.value.length<8)return resetStatus.textContent='Use at least 8 characters.';if(newPassword.value!==confirmPassword.value)return resetStatus.textContent='Passwords do not match.';busy(resetBtn,true,'Updating…');const {error}=await sb.auth.updateUser({password:newPassword.value});if(error){busy(resetBtn,false,'Update password');resetStatus.textContent=error.message;return}resetStatus.textContent='Password updated. Opening admin…';setTimeout(()=>location.href='/admin',700)}
}
async function boot(){
  if(location.pathname==='/admin-reset')return resetPage();
  if(location.pathname==='/admin-login')return loginPage();
  const u=await currentMember();if(u===null){history.replaceState({},'','/admin-login');return loginPage()}if(u===false){await sb.auth.signOut();location.href='/';return}shell(u)
}
function shell(user){
  currentUser=user;currentRole=user.nexusRole||'staff';
  app.innerHTML='<div class="top"><div class="topin"><div><div class="brand">NEXUS ADMIN</div><div class="who">'+esc(user.email)+' · '+esc(currentRole==='owner'?'Owner':'Team member')+'</div></div><button id="signout" class="btn secondary">Sign out</button></div></div><div class="shell layout"><aside id="side" class="side"></aside><main id="main" class="main"><section id="panel" class="panel"></section></main></div>';
  const items=[['events','Events'],['content','Stories & Episodes'],['gallery','Gallery'],['applications','Applications'],['messages','Messages']];
  if(currentRole==='owner')items.splice(1,0,['forms','Forms']);
  if(currentRole==='owner')items.push(['general','General Settings'],['announcements','Pop-ups'],['team','Team Access']);
  side.innerHTML=items.map(([k,l])=>'<button data-sec="'+k+'"><span>'+l+'</span></button>').join('');
  side.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.sec;render()});signout.onclick=async()=>{await sb.auth.signOut();location.href='/'};render()
}
function navState(){side.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.sec===active))}
async function render(){navState();panel.innerHTML='<div class="empty">Loading…</div>';const map={events:eventsView,forms:formsView,content:contentView,gallery:galleryView,applications:applicationsView,general:generalView,announcements:announcementsView,messages:messagesView,team:teamView};return (map[active]||eventsView)()}
async function optimizeImage(file,max=1800,quality=.82){
  if(!file||!file.type.startsWith('image/'))return file;
  let source=null,width=0,height=0,cleanup=()=>{};
  try{
    if('createImageBitmap' in window){
      const bmp=await createImageBitmap(file);source=bmp;width=bmp.width;height=bmp.height;cleanup=()=>bmp.close?.();
    }else{
      const url=URL.createObjectURL(file),img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url});source=img;width=img.naturalWidth;height=img.naturalHeight;cleanup=()=>URL.revokeObjectURL(url);
    }
    const scale=Math.min(1,max/Math.max(width,height)),w=Math.max(1,Math.round(width*scale)),h=Math.max(1,Math.round(height*scale));
    const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(source,0,0,w,h);
    const blob=await new Promise(r=>canvas.toBlob(r,'image/webp',quality));cleanup();
    return blob?new File([blob],(file.name.replace(/\.[^.]+$/,'')||'image')+'.webp',{type:'image/webp'}):file;
  }catch(e){try{cleanup()}catch{};return file}
}
async function upload(file,folder){
  const opt=await optimizeImage(file);const safe=(opt.name||'image.webp').replace(/[^a-zA-Z0-9._-]/g,'-'),path=folder+'/'+Date.now()+'-'+safe;
  const {error}=await sb.storage.from('nexus-media').upload(path,opt,{cacheControl:'31536000',upsert:false,contentType:opt.type});if(error)throw error;return sb.storage.from('nexus-media').getPublicUrl(path).data.publicUrl
}
async function eventsView(){
  const [{data:events,error},{data:regs,error:re}]=await Promise.all([sb.from('events').select('*').order('event_date',{ascending:false}),sb.from('registrations').select('*').order('created_at',{ascending:false})]);if(error||re)return panel.innerHTML='<div class="empty">'+esc((error||re).message)+'</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Events</h2><p>Internal NEXUS registration or an external Google Form.</p></div><div><input class="search" id="eventSearch" placeholder="Search events"> <button class="btn" id="addEvent">Create event</button></div></div><div id="eventsTable"></div>';
  const draw=qry=>{const list=events.filter(x=>(x.title+' '+(x.location||'')).toLowerCase().includes(qry.toLowerCase()));eventsTable.innerHTML=list.length?'<div class="tablewrap"><table><thead><tr><th>Event</th><th>Date</th><th>Registration</th><th>Registrants</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+list.map(x=>'<tr><td class="wrap"><b>'+esc(x.title)+'</b><div class="muted">'+esc(x.location||'')+'</div></td><td>'+esc(fmt(x.event_date))+'</td><td>'+esc(x.registration_method==='external'?'External form':'NEXUS form')+'</td><td>'+regs.filter(r=>r.event_id===x.id).length+'</td><td><span class="status '+(x.published?'published':'draft')+'">'+(x.published?'Published':'Draft')+'</span></td><td><div class="actions"><button class="btn small secondary" data-reg="'+x.id+'">Registrants</button>'+((currentRole==='owner'||!x.published)?'<button class="btn small secondary" data-edit="'+x.id+'">Edit</button>':'')+(currentRole==='owner'?'<button class="btn small danger" data-del="'+x.id+'">Delete</button>':'')+'</div></td></tr>').join('')+'</tbody></table></div>':'<div class="empty">No events.</div>';
  eventsTable.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>eventEditor(events.find(x=>x.id===b.dataset.edit)));
  eventsTable.querySelectorAll('[data-reg]').forEach(b=>b.onclick=()=>registrantsView(events.find(x=>x.id===b.dataset.reg),regs.filter(r=>r.event_id===b.dataset.reg)));
  eventsTable.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this event? Linked registrations will also be deleted.'))return;const {error}=await sb.from('events').delete().eq('id',b.dataset.del);if(error)return toast(error.message);eventsView()})};
  draw('');eventSearch.oninput=e=>draw(e.target.value);addEvent.onclick=()=>eventEditor({})
}
async function registrantsView(event,rows){
  let form=null;if(event.form_id){const {data}=await sb.from('forms').select('*').eq('id',event.form_id).maybeSingle();form=data}
  if(!form){const {data}=await sb.from('forms').select('*').eq('form_key','default-event-registration').maybeSingle();form=data}
  const preferred=(form?.fields||[]).map(f=>f.name),keys=[...new Set([...preferred,'full_name','email','phone',...rows.flatMap(r=>Object.keys(parseExtra(r))),'created_at'])].filter(k=>k!=='extra_data'&&k!=='id'&&k!=='event_id');
  const label=k=>form?.fields?.find(f=>f.name===k)?.label||k.split('_').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');
  panel.innerHTML='<div class="toolbar"><div><h2>'+esc(event.title)+'</h2><p>'+rows.length+' registration'+(rows.length===1?'':'s')+' · columns follow the active form.</p></div><div><button class="btn secondary" id="backEvents">Back</button> <button class="btn" id="exportCsv">Export full CSV</button></div></div>'+(event.registration_method==='external'?'<div class="notice">This event uses an external form, so responses live in that provider unless separately imported into NEXUS.</div>':'')+'<div class="tablewrap"><table><thead><tr>'+keys.map(k=>'<th>'+esc(label(k))+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>'<td>'+esc(k==='created_at'?fmt(r[k]):(parseExtra(r)[k]??r[k]??'—'))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
  backEvents.onclick=eventsView;exportCsv.onclick=()=>downloadCsv(rows,slugify(event.title)+'-registrants.csv',preferred)
}
async function eventEditor(x){
  const {data:forms=[]}=await sb.from('forms').select('id,title,form_key').eq('form_type','event').eq('published',true).order('title');const formOptions=forms.map(f=>'<option value="'+f.id+'" '+(x.form_id===f.id?'selected':'')+'>'+esc(f.title)+'</option>').join('');
  panel.innerHTML='<div class="toolbar"><div><h2>'+(x.id?'Edit event':'Create event')+'</h2><p>Choose NEXUS form registration or send visitors to a Google Form.</p></div><button class="btn secondary" id="backEvents">Back</button></div><form id="eventForm" class="formgrid"><div class="field"><label>Title</label><input name="title" value="'+esc(x.title||'')+'" required></div><div class="field"><label>Date & time</label><input type="datetime-local" name="event_date" value="'+(x.event_date?new Date(x.event_date).toISOString().slice(0,16):'')+'" required></div><div class="field"><label>Location</label><input name="location" value="'+esc(x.location||'')+'"></div><div class="field"><label>Cover image</label><input type="file" id="eventCover" accept="image/*"></div><div class="field full"><label>Summary</label><textarea name="summary">'+esc(x.summary||'')+'</textarea></div><div class="field full"><label>Description</label><textarea name="description">'+esc(x.description||'')+'</textarea></div><div class="field"><label>Registration method</label><select id="registrationMethod" name="registration_method"><option value="nexus" '+(x.registration_method!=='external'?'selected':'')+'>NEXUS form</option><option value="external" '+(x.registration_method==='external'?'selected':'')+'>External / Google Form</option></select></div><div class="field" id="internalFormField"><label>NEXUS form</label><select name="form_id"><option value="">Default event form</option>'+formOptions+'</select></div><div class="field full" id="externalFormField"><label>External form URL</label><input type="url" name="external_form_url" placeholder="https://forms.gle/..." value="'+esc(x.external_form_url||'')+'"><small>When selected, Register opens this URL instead of the NEXUS form.</small></div><div class="field full"><div class="publishbox"><div><b>Publishing</b><div class="muted">Keep drafts private until they are ready.</div></div>'+(currentRole==='owner'?'<label><input type="checkbox" name="published" '+(x.published?'checked':'')+'> Published</label>':'<span class="status draft">Owner approval required</span>')+'</div></div><div class="field full"><button class="btn" id="saveEvent">Save event</button></div></form>';
  const sync=()=>{const ext=registrationMethod.value==='external';externalFormField.style.display=ext?'flex':'none';internalFormField.style.display=ext?'none':'flex'};registrationMethod.onchange=sync;sync();backEvents.onclick=eventsView;
  eventForm.onsubmit=async e=>{e.preventDefault();busy(saveEvent,true,'Saving…');const f=new FormData(eventForm);let image=x.image_url||null;try{if(eventCover.files[0])image=await upload(eventCover.files[0],'events')}catch(err){busy(saveEvent,false,'Save event');return toast(err.message)}const method=f.get('registration_method'),payload={title:f.get('title').trim(),slug:x.slug||slugify(f.get('title')),summary:f.get('summary').trim(),description:f.get('description').trim(),event_date:new Date(f.get('event_date')).toISOString(),location:f.get('location').trim(),image_url:image,registration_method:method,external_form_url:method==='external'?(f.get('external_form_url').trim()||null):null,form_id:method==='nexus'?(f.get('form_id')||null):null,published:currentRole==='owner'?eventForm.published.checked:false};const cmd=x.id?sb.from('events').update(payload).eq('id',x.id):sb.from('events').insert(payload);const {error}=await cmd;if(error){busy(saveEvent,false,'Save event');return toast(error.message)}toast('Event saved.');eventsView()}
}
async function formsView(){
  const {data:forms=[],error}=await sb.from('forms').select('*').order('form_type').order('title');if(error)return panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Forms</h2><p>Edit the default event form and Ambassador / Partner applications without code.</p></div><button class="btn" id="newForm">New event form</button></div><div class="tablewrap"><table><thead><tr><th>Form</th><th>Type</th><th>Fields</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+forms.map(f=>'<tr><td class="wrap"><b>'+esc(f.title)+'</b><div class="muted">'+esc(f.description||f.form_key||'')+'</div></td><td>'+esc(f.form_type)+(f.pathway?' · '+esc(f.pathway):'')+'</td><td>'+((f.fields||[]).length)+'</td><td><span class="status '+(f.published?'published':'draft')+'">'+(f.published?'Published':'Draft')+'</span></td><td><button class="btn small secondary" data-edit="'+f.id+'">Edit form</button></td></tr>').join('')+'</tbody></table></div>';
  panel.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>formEditor(forms.find(f=>f.id===b.dataset.edit)));newForm.onclick=()=>formEditor({form_type:'event',fields:[],published:true})
}
function formEditor(form){
  let fields=structuredClone(form.fields||[]);
  panel.innerHTML='<div class="toolbar"><div><h2>'+(form.id?'Edit form':'New event form')+'</h2><p>Changes automatically control future NEXUS submissions and CSV columns.</p></div><button class="btn secondary" id="backForms">Back</button></div><form id="formEditor" class="formgrid"><div class="field"><label>Title</label><input name="title" value="'+esc(form.title||'')+'" required></div><div class="field"><label>Submit button label</label><input name="submit_label" value="'+esc(form.submit_label||'Submit')+'"></div><div class="field full"><label>Description</label><textarea name="description">'+esc(form.description||'')+'</textarea></div><div class="field"><label>Success title</label><input name="success_title" value="'+esc(form.success_title||'Thanks!')+'"></div><div class="field"><label>Success message</label><input name="success_message" value="'+esc(form.success_message||'Your response has been received.')+'"></div><div class="field full"><div class="sectionbox"><div class="toolbar"><div><h3>Form fields</h3><p>Text, email, phone, textarea and select are supported.</p></div><button type="button" id="addField" class="btn small">Add field</button></div><div id="fieldBuilder" class="builder"></div></div></div><div class="field full"><div class="publishbox"><div><b>Form availability</b><div class="muted">Unpublish to stop using this form on the website.</div></div><label><input type="checkbox" name="published" '+(form.published!==false?'checked':'')+'> Published</label></div></div><div class="field full"><button id="saveForm" class="btn">Save form</button></div></form>';
  const draw=()=>{fieldBuilder.innerHTML=fields.map((f,i)=>'<div class="fieldrow" data-i="'+i+'"><div class="wide"><label>Label</label><input data-k="label" value="'+esc(f.label||'')+'"></div><div><label>Name</label><input data-k="name" value="'+esc(f.name||'')+'"></div><div><label>Type</label><select data-k="type">'+['text','email','tel','textarea','select'].map(t=>'<option '+(f.type===t?'selected':'')+'>'+t+'</option>').join('')+'</select></div><div><label>Required</label><select data-k="required"><option value="false" '+(!f.required?'selected':'')+'>No</option><option value="true" '+(f.required?'selected':'')+'>Yes</option></select></div><button type="button" class="btn small danger" data-remove="'+i+'">Remove</button><div class="wide"><label>Options (comma-separated, for select)</label><input data-k="options" value="'+esc((f.options||[]).join(', '))+'"></div></div>').join('');fieldBuilder.querySelectorAll('[data-k]').forEach(el=>el.oninput=()=>{const row=el.closest('.fieldrow'),i=Number(row.dataset.i),k=el.dataset.k;fields[i][k]=k==='required'?el.value==='true':k==='options'?tags(el.value):el.value});fieldBuilder.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{fields.splice(Number(b.dataset.remove),1);draw()})};draw();addField.onclick=()=>{fields.push({name:'field_'+(fields.length+1),type:'text',label:'New field',required:false});draw()};backForms.onclick=formsView;
  const formEl=document.getElementById('formEditor');formEl.onsubmit=async e=>{e.preventDefault();const names=fields.map(x=>String(x.name||'').trim()),bad=names.find(n=>!n||!/^[_a-z][_a-z0-9]*$/i.test(n));if(bad!==undefined)return toast('Field names must start with a letter or underscore and use only letters, numbers and underscores.');if(new Set(names.map(n=>n.toLowerCase())).size!==names.length)return toast('Each form field needs a unique field name.');if(fields.some(x=>!String(x.label||'').trim()))return toast('Every form field needs a label.');busy(saveForm,true,'Saving…');const fd=new FormData(formEl),payload={title:fd.get('title').trim(),description:fd.get('description').trim(),submit_label:fd.get('submit_label').trim()||'Submit',success_title:fd.get('success_title').trim(),success_message:fd.get('success_message').trim(),fields,published:formEl.published.checked,form_type:form.form_type||'event',form_key:form.form_key||null,pathway:form.pathway||null};const cmd=form.id?sb.from('forms').update(payload).eq('id',form.id):sb.from('forms').insert(payload);const {error}=await cmd;if(error){busy(saveForm,false,'Save form');return toast(error.message)}toast('Form saved.');formsView()}
}
async function contentView(){
  const {data:items=[],error}=await sb.from('stories').select('*').in('category',['story','episode','guide']).order('created_at',{ascending:false});if(error)return panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Stories & Episodes</h2><p>Tags power discovery and category filtering.</p></div><div><input class="search" id="contentSearch" placeholder="Search"> <button class="btn" id="addContent">Create content</button></div></div><div id="contentTable"></div>';
  const draw=s=>{const list=items.filter(x=>(x.title+' '+x.category+' '+(x.tags||[]).join(' ')).toLowerCase().includes(s.toLowerCase()));contentTable.innerHTML='<div class="tablewrap"><table><thead><tr><th>Title</th><th>Type</th><th>Tags</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+list.map(x=>'<tr><td class="wrap"><b>'+esc(x.title)+'</b><div class="muted">'+esc(x.author||'')+'</div></td><td>'+esc(x.category)+'</td><td class="wrap">'+(x.tags||[]).map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</td><td><span class="status '+(x.published?'published':'draft')+'">'+(x.published?'Published':'Draft')+'</span></td><td><div class="actions">'+(currentRole==='owner'?'<button class="btn small secondary" data-pub="'+x.id+'">'+(x.published?'Unpublish':'Publish')+'</button>':'')+((currentRole==='owner'||!x.published)?'<button class="btn small secondary" data-edit="'+x.id+'">Edit</button>':'')+(currentRole==='owner'?'<button class="btn small danger" data-del="'+x.id+'">Delete</button>':'')+'</div></td></tr>').join('')+'</tbody></table></div>';contentTable.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>contentEditor(items.find(x=>x.id===b.dataset.edit)));contentTable.querySelectorAll('[data-pub]').forEach(b=>b.onclick=async()=>{const x=items.find(y=>y.id===b.dataset.pub),on=!x.published,{error}=await sb.from('stories').update({published:on,published_at:on?(x.published_at||new Date().toISOString()):null}).eq('id',x.id);if(error)return toast(error.message);contentView()});contentTable.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this content item?')){const {error}=await sb.from('stories').delete().eq('id',b.dataset.del);if(error)return toast(error.message);contentView()}})};draw('');contentSearch.oninput=e=>draw(e.target.value);addContent.onclick=()=>contentEditor({category:'story'})
}
function contentEditor(x){
  panel.innerHTML='<div class="toolbar"><div><h2>'+(x.id?'Edit content':'Create content')+'</h2><p>Episodes accept YouTube URLs in the Media field.</p></div><button class="btn secondary" id="backContent">Back</button></div><form id="contentForm" class="formgrid"><div class="field"><label>Title</label><input name="title" value="'+esc(x.title||'')+'" required></div><div class="field"><label>Type</label><select name="category"><option value="story" '+(x.category==='story'?'selected':'')+'>Story</option><option value="episode" '+(x.category==='episode'?'selected':'')+'>Episode</option><option value="guide" '+(x.category==='guide'?'selected':'')+'>Guide</option></select></div><div class="field"><label>Author</label><input name="author" value="'+esc(x.author||'')+'"></div><div class="field"><label>Media / YouTube URL</label><input type="url" name="media_url" value="'+esc(x.media_url||'')+'"></div><div class="field full"><label>Tags</label><input name="tags" placeholder="BIM, estimating, careers" value="'+esc((x.tags||[]).join(', '))+'"></div><div class="field full"><label>Excerpt</label><textarea name="excerpt">'+esc(x.excerpt||'')+'</textarea></div><div class="field full"><label>Body</label><textarea name="body" style="min-height:220px">'+esc(x.body||'')+'</textarea></div><div class="field"><label>Cover image</label><input type="file" id="contentCover" accept="image/*"></div><div class="field full"><div class="publishbox"><div><b>Publishing</b><div class="muted">Drafts stay out of the public site.</div></div>'+(currentRole==='owner'?'<label><input type="checkbox" name="published" '+(x.published?'checked':'')+'> Published</label>':'<span class="status draft">Owner approval required</span>')+'</div></div><div class="field full"><button id="saveContent" class="btn">Save content</button></div></form>';
  backContent.onclick=contentView;contentForm.onsubmit=async e=>{e.preventDefault();busy(saveContent,true,'Saving…');const f=new FormData(contentForm);let image=x.image_url||null;try{if(contentCover.files[0])image=await upload(contentCover.files[0],'content')}catch(err){busy(saveContent,false,'Save content');return toast(err.message)}const pub=currentRole==='owner'?contentForm.published.checked:false,payload={title:f.get('title').trim(),slug:x.slug||slugify(f.get('title'))+'-'+Date.now().toString().slice(-5),category:f.get('category'),author:f.get('author').trim(),excerpt:f.get('excerpt').trim(),body:f.get('body').trim(),media_url:f.get('media_url').trim()||null,image_url:image,tags:tags(f.get('tags')),published:pub,published_at:pub?(x.published_at||new Date().toISOString()):null};const cmd=x.id?sb.from('stories').update(payload).eq('id',x.id):sb.from('stories').insert(payload);const {error}=await cmd;if(error){busy(saveContent,false,'Save content');return toast(error.message)}toast('Content saved.');contentView()}
}
async function galleryView(){
  const {data:items=[],error}=await sb.from('gallery_items').select('*').order('created_at',{ascending:false});if(error)return panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Gallery</h2><p>Newest uploads appear first on the public gallery. Tags create category filters.</p></div><div><input class="search" id="gallerySearch" placeholder="Search"> <button class="btn" id="addGallery">Upload image</button></div></div><div id="galleryTable"></div>';
  const draw=s=>{const list=items.filter(x=>(x.title+' '+(x.caption||'')+' '+(x.tags||[]).join(' ')).toLowerCase().includes(s.toLowerCase()));galleryTable.innerHTML='<div class="tablewrap"><table><thead><tr><th>Image</th><th>Title</th><th>Tags</th><th>Uploaded</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+list.map(x=>'<tr><td><img class="thumb" src="'+esc(x.image_url)+'"></td><td class="wrap"><b>'+esc(x.title||'Image')+'</b><div class="muted">'+esc(x.caption||'')+'</div></td><td class="wrap">'+(x.tags||[]).map(t=>'<span class="tag">'+esc(t)+'</span>').join('')+'</td><td>'+esc(fmt(x.created_at))+'</td><td><span class="status '+(x.published?'published':'draft')+'">'+(x.published?'Published':'Draft')+'</span></td><td><div class="actions">'+((currentRole==='owner'||!x.published)?'<button class="btn small secondary" data-edit="'+x.id+'">Edit</button>':'')+(currentRole==='owner'?'<button class="btn small danger" data-del="'+x.id+'">Delete</button>':'')+'</div></td></tr>').join('')+'</tbody></table></div>';galleryTable.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>galleryEditor(items.find(x=>x.id===b.dataset.edit)));galleryTable.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this gallery item?')){const {error}=await sb.from('gallery_items').delete().eq('id',b.dataset.del);if(error)return toast(error.message);galleryView()}})};draw('');gallerySearch.oninput=e=>draw(e.target.value);addGallery.onclick=()=>galleryEditor({})
}
function galleryEditor(x){
  panel.innerHTML='<div class="toolbar"><div><h2>'+(x.id?'Edit gallery item':'Upload gallery image')+'</h2><p>Images are resized and converted to WebP before upload.</p></div><button class="btn secondary" id="backGallery">Back</button></div><form id="galleryForm" class="formgrid"><div class="field"><label>Title</label><input name="title" value="'+esc(x.title||'')+'" required></div><div class="field"><label>Image '+(x.id?'(optional replacement)':'')+'</label><input type="file" id="galleryFile" accept="image/*" '+(x.id?'':'required')+'></div><div class="field full"><label>Caption</label><textarea name="caption">'+esc(x.caption||'')+'</textarea></div><div class="field full"><label>Tags / categories</label><input name="tags" placeholder="Event, Team, Workshop" value="'+esc((x.tags||[]).join(', '))+'"></div><div class="field full"><div class="publishbox"><div><b>Publishing</b></div>'+(currentRole==='owner'?'<label><input type="checkbox" name="published" '+(x.id?(x.published?'checked':''):'checked')+'> Published</label>':'<span class="status draft">Owner approval required</span>')+'</div></div><div class="field full"><button id="saveGallery" class="btn">'+(x.id?'Save changes':'Upload')+'</button></div></form>';
  backGallery.onclick=galleryView;galleryForm.onsubmit=async e=>{e.preventDefault();busy(saveGallery,true,'Saving…');const f=new FormData(galleryForm);let url=x.image_url||null;try{if(galleryFile.files[0])url=await upload(galleryFile.files[0],'gallery')}catch(err){busy(saveGallery,false,x.id?'Save changes':'Upload');return toast(err.message)}const payload={title:f.get('title').trim(),caption:f.get('caption').trim(),tags:tags(f.get('tags')),image_url:url,published:currentRole==='owner'?galleryForm.published.checked:false};const cmd=x.id?sb.from('gallery_items').update(payload).eq('id',x.id):sb.from('gallery_items').insert(payload);const {error}=await cmd;if(error){busy(saveGallery,false,x.id?'Save changes':'Upload');return toast(error.message)}toast('Gallery saved.');galleryView()}
}
async function applicationsView(){
  const {data:items=[],error}=await sb.from('join_registrations').select('*').order('created_at',{ascending:false});if(error)return panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Applications</h2><p>Ambassador and Partner responses. Edit their questions under Forms.</p></div><div><input class="search" id="appSearch" placeholder="Search"> <button class="btn secondary" id="exportApps">Export CSV</button></div></div><div id="appsTable"></div>';
  const draw=s=>{const list=items.filter(x=>JSON.stringify(x).toLowerCase().includes(s.toLowerCase()));appsTable.innerHTML='<div class="tablewrap"><table><thead><tr><th>Applicant</th><th>Pathway</th><th>Contact</th><th>Details</th><th>Status</th><th>Actions</th></tr></thead><tbody>'+list.map(x=>'<tr><td><b>'+esc(x.full_name)+'</b><div class="muted">'+esc(fmt(x.created_at))+'</div></td><td>'+esc(x.pathway)+'</td><td>'+esc(x.email)+'<br>'+esc(x.phone||'—')+'</td><td class="wrap">'+Object.entries(parseExtra(x)).filter(([k])=>!['full_name','email','phone','pathway'].includes(k)).map(([k,v])=>'<div><b>'+esc(k.replaceAll('_',' '))+':</b> '+esc(v)+'</div>').join('')+'</td><td><span class="status '+esc(x.status||'pending')+'">'+esc(x.status||'pending')+'</span></td><td>'+(currentRole==='owner'?'<div class="actions"><button class="btn small secondary" data-status="approved" data-id="'+x.id+'">Approve</button><button class="btn small secondary" data-status="rejected" data-id="'+x.id+'">Reject</button></div>':'Owner approval required')+'</td></tr>').join('')+'</tbody></table></div>';appsTable.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{const {error}=await sb.from('join_registrations').update({status:b.dataset.status}).eq('id',b.dataset.id);if(error)return toast(error.message);applicationsView()})};draw('');appSearch.oninput=e=>draw(e.target.value);exportApps.onclick=()=>downloadCsv(items,'nexus-applications.csv',['pathway','full_name','email','phone','occupation','university_or_company','city','reason','status','created_at'])
}

async function generalView(){
  if(currentRole!=='owner')return panel.innerHTML='<div class="empty">Owner authorization required.</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>General Settings</h2><p>Manage branding, logo, tagline, themes, page content, footer, links and core website messaging.</p></div></div><div class="cards"><button class="metric" id="openBranding" style="text-align:left;cursor:pointer"><b style="font-size:18px">Branding & Logo</b><div class="muted">Logo, brand name, tagline, About and Join messaging.</div></button><button class="metric" id="openTheme" style="text-align:left;cursor:pointer"><b style="font-size:18px">Theme</b><div class="muted">Preset palettes or a custom website palette.</div></button><button class="metric" id="openPages" style="text-align:left;cursor:pointer"><b style="font-size:18px">Pages, Footer & Links</b><div class="muted">Page copy, SEO, stay-close footer and social/media links.</div></button></div>';
  openBranding.onclick=brandingView;openTheme.onclick=appearanceView;openPages.onclick=pagesView
}
async function brandingView(){
  const {data:s,error}=await sb.from('site_settings').select('*').eq('id',1).single();if(error)return panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Branding & Logo</h2><p>This controls the public NEXUS lockup and core site messaging.</p></div><button class="btn secondary" id="backGeneral">Back to General Settings</button></div><form id="brandingForm" class="formgrid"><div class="field"><label>Brand name</label><input name="brand_name" value="'+esc(s.brand_name||'NEXUS')+'"></div><div class="field"><label>Tagline</label><input name="brand_tagline" value="'+esc(s.brand_tagline||'Construction Without Borders')+'"></div><div class="field"><label>Logo image</label><input type="file" id="brandLogoFile" accept="image/png,image/jpeg,image/webp,image/svg+xml"></div><div class="field"><label>Logo alt text</label><input name="logo_alt" value="'+esc(s.logo_alt||s.brand_name||'NEXUS')+'"></div><div class="field full"><div class="sectionbox"><h3>Current logo</h3><div id="logoPreview" style="min-height:70px;display:flex;align-items:center;gap:16px">'+(s.logo_url?'<img src="'+esc(s.logo_url)+'" alt="'+esc(s.logo_alt||'NEXUS')+'" style="max-width:220px;max-height:70px;object-fit:contain">':'<b style="font-size:28px;color:var(--p)">'+esc(s.brand_name||'NEXUS')+'</b>')+'</div><label style="display:block;margin-top:12px"><input type="checkbox" name="remove_logo"> Remove uploaded logo and use text brand</label></div></div><div class="field"><label>About heading</label><input name="about_heading" value="'+esc(s.about_heading||'Construction without borders.')+'"></div><div class="field"><label>Contact email</label><input type="email" name="contact_email" value="'+esc(s.contact_email||'')+'"></div><div class="field full"><label>About main text</label><textarea name="about_text" rows="5">'+esc(s.about_text||'')+'</textarea></div><div class="field"><label>Join heading</label><input name="join_heading" value="'+esc(s.join_heading||'Join NEXUS')+'"></div><div class="field"><label>Join intro</label><input name="join_intro" value="'+esc(s.join_intro||'Choose how you would like to connect with the NEXUS community.')+'"></div><div class="field full"><button class="btn" id="saveBranding">Save branding & website identity</button></div></form>';
  backGeneral.onclick=generalView;
  brandLogoFile.onchange=()=>{const file=brandLogoFile.files[0];if(file){const url=URL.createObjectURL(file);logoPreview.innerHTML='<img src="'+url+'" alt="Logo preview" style="max-width:220px;max-height:70px;object-fit:contain">'}};
  brandingForm.onsubmit=async e=>{e.preventDefault();busy(saveBranding,true,'Saving…');const fd=new FormData(brandingForm);let logo=s.logo_url||null;try{if(fd.get('remove_logo'))logo=null;else if(brandLogoFile.files[0])logo=await upload(brandLogoFile.files[0],'branding')}catch(err){busy(saveBranding,false,'Save branding & website identity');return toast(err.message)}
    const payload={brand_name:fd.get('brand_name').trim()||'NEXUS',brand_tagline:fd.get('brand_tagline').trim()||'Construction Without Borders',logo_url:logo,logo_alt:fd.get('logo_alt').trim()||fd.get('brand_name').trim()||'NEXUS',about_heading:fd.get('about_heading').trim(),about_text:fd.get('about_text').trim(),contact_email:fd.get('contact_email').trim()||null,join_heading:fd.get('join_heading').trim()||'Join NEXUS',join_intro:fd.get('join_intro').trim()||'Choose how you would like to connect with the NEXUS community.',updated_at:new Date().toISOString()};
    const {error}=await sb.from('site_settings').update(payload).eq('id',1);busy(saveBranding,false,'Save branding & website identity');if(error)return toast(error.message);sessionStorage.removeItem('nexus_site_bundle_v3');alert('Branding saved. The logo and tagline will now be used across the public site.');brandingView()
  }
}
async function pagesView(){
  const [{data:pages=[]},{data:links=[]},{data:settings}]=await Promise.all([sb.from('site_pages').select('*').order('slug'),sb.from('social_links').select('*').order('sort_order'),sb.from('site_settings').select('*').eq('id',1).single()]);
  panel.innerHTML='<div class="toolbar"><div><h2>Pages, Footer & Links</h2><p>Edit page headings, SEO metadata, footer copy and social/media links.</p></div><button class="btn secondary" id="backGeneral">Back to General Settings</button></div><div class="sectionbox"><h3>Pages</h3><div class="tablewrap"><table><thead><tr><th>Page</th><th>SEO title</th><th>Status</th><th></th></tr></thead><tbody>'+pages.map(p=>'<tr><td><b>/'+esc(p.slug)+'</b><div class="muted">'+esc(p.title)+'</div></td><td class="wrap">'+esc(p.seo_title||'')+'</td><td><span class="status '+(p.published?'published':'draft')+'">'+(p.published?'Published':'Draft')+'</span></td><td><button class="btn small secondary" data-page="'+p.id+'">Edit</button></td></tr>').join('')+'</tbody></table></div></div><div class="sectionbox" style="margin-top:16px"><div class="toolbar"><h3>Footer & social links</h3><button class="btn small" id="addSocial">Add link</button></div><form id="footerForm" class="formgrid"><div class="field"><label>Stay-close kicker</label><input name="stay_close_kicker" value="'+esc(settings.footer_config?.stay_close_kicker||'STAY CLOSE')+'"></div><div class="field"><label>Stay-close title</label><input name="stay_close_title" value="'+esc(settings.footer_config?.stay_close_title||'Join NEXUS.')+'"></div><div class="field full"><label>Stay-close text</label><textarea name="stay_close_text">'+esc(settings.footer_config?.stay_close_text||'')+'</textarea></div><div class="field"><label>Brand line</label><input name="brand_line" value="'+esc(settings.footer_config?.brand_line||'Construction Without Borders')+'"></div><div class="field"><label>Powered by</label><input name="powered_by" value="'+esc(settings.footer_config?.powered_by||'Powered by Next Gen Plex')+'"></div><div class="field full"><button class="btn" id="saveFooter">Save footer</button></div></form><div id="socialList" class="tablewrap" style="margin-top:16px"><table><thead><tr><th>Label</th><th>URL</th><th>Status</th><th></th></tr></thead><tbody>'+links.map(l=>'<tr><td>'+esc(l.label)+'</td><td class="wrap">'+esc(l.url)+'</td><td>'+(l.enabled?'Enabled':'Hidden')+'</td><td><button class="btn small secondary" data-social="'+l.id+'">Edit</button></td></tr>').join('')+'</tbody></table></div></div>';
  backGeneral.onclick=generalView;panel.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>pageEditor(pages.find(p=>p.id===b.dataset.page)));panel.querySelectorAll('[data-social]').forEach(b=>b.onclick=()=>socialEditor(links.find(l=>l.id===b.dataset.social)));addSocial.onclick=()=>socialEditor({});
  footerForm.onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(footerForm));const {error}=await sb.from('site_settings').update({footer_config:f}).eq('id',1);if(error)return toast(error.message);toast('Footer saved.')}
}
function pageEditor(p){
  panel.innerHTML='<div class="toolbar"><div><h2>Edit /'+esc(p.slug)+'</h2><p>Page-level copy and search metadata.</p></div><button class="btn secondary" id="backPages">Back</button></div><form id="pageForm" class="formgrid"><div class="field"><label>Page title</label><input name="title" value="'+esc(p.title||'')+'"></div><div class="field"><label>Kicker</label><input name="kicker" value="'+esc(p.kicker||'')+'"></div><div class="field full"><label>Description</label><textarea name="description">'+esc(p.description||'')+'</textarea></div><div class="field"><label>SEO title</label><input name="seo_title" value="'+esc(p.seo_title||'')+'"></div><div class="field"><label>Banner color</label><input type="color" name="banner_color" value="'+esc(p.banner_color||'#4B2E92')+'"></div><div class="field full"><label>SEO description</label><textarea name="seo_description">'+esc(p.seo_description||'')+'</textarea></div><div class="field full"><div class="publishbox"><b>Public page</b><label><input type="checkbox" name="published" '+(p.published?'checked':'')+'> Published</label></div></div><div class="field full"><button class="btn" id="savePage">Save page</button></div></form>';
  backPages.onclick=pagesView;pageForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(pageForm),payload={title:f.get('title').trim(),kicker:f.get('kicker').trim(),description:f.get('description').trim(),seo_title:f.get('seo_title').trim(),seo_description:f.get('seo_description').trim(),banner_color:f.get('banner_color'),published:pageForm.published.checked,updated_at:new Date().toISOString()};const {error}=await sb.from('site_pages').update(payload).eq('id',p.id);if(error)return toast(error.message);toast('Page saved.');pagesView()}
}
function socialEditor(x){
  panel.innerHTML='<div class="toolbar"><h2>'+(x.id?'Edit link':'Add social / media link')+'</h2><button class="btn secondary" id="backPages">Back</button></div><form id="socialForm" class="formgrid"><div class="field"><label>Label</label><input name="label" value="'+esc(x.label||'')+'" required></div><div class="field"><label>URL</label><input name="url" value="'+esc(x.url||'')+'" required></div><div class="field"><label>Order</label><input type="number" name="sort_order" value="'+esc(x.sort_order??0)+'"></div><div class="field"><label><input type="checkbox" name="enabled" '+(x.enabled!==false?'checked':'')+'> Enabled</label></div><div class="field full"><button class="btn">Save link</button></div></form>';
  backPages.onclick=pagesView;socialForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(socialForm),payload={label:f.get('label').trim(),url:f.get('url').trim(),sort_order:Number(f.get('sort_order')||0),enabled:socialForm.enabled.checked,updated_at:new Date().toISOString()};const cmd=x.id?sb.from('social_links').update(payload).eq('id',x.id):sb.from('social_links').insert(payload);const {error}=await cmd;if(error)return toast(error.message);toast('Link saved.');pagesView()}
}
async function appearanceView(){
  const {data:s,error}=await sb.from('site_settings').select('*').eq('id',1).single();if(error)return panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';
  const themes=[
    {key:'nexus-purple',name:'NEXUS Purple',p:'#4B2E92',a:'#C9B8F5',bg:'#F5F2FC',text:'#1A1730'},
    {key:'builder-orange',name:'Construction Orange',p:'#E05A1A',a:'#F4C09C',bg:'#F7F3EF',text:'#252321'},
    {key:'site-blue',name:'Site Blue',p:'#124E78',a:'#8DC6E8',bg:'#F2F7FA',text:'#132632'},
    {key:'charcoal-lime',name:'Charcoal + Lime',p:'#252A2E',a:'#C9E265',bg:'#F5F6F2',text:'#171A1D'},
    {key:'forest-sand',name:'Forest + Sand',p:'#315B49',a:'#D9C79E',bg:'#F7F4ED',text:'#18241E'},
    {key:'custom',name:'Custom',p:s.custom_theme?.primary||'#4B2E92',a:s.custom_theme?.accent||'#C9B8F5',bg:s.custom_theme?.background||'#F5F2FC',text:s.custom_theme?.text||'#1A1730'}
  ];
  panel.innerHTML='<div class="toolbar"><div><h2>Theme</h2><p>Choose a preset or apply a custom palette. Page hero overlays follow the active theme unless a page has a manual override.</p></div><button class="btn secondary" id="backGeneral">Back to General Settings</button></div><div class="palette" id="themeGrid">'+themes.map(t=>'<button class="theme '+(s.theme_key===t.key?'active':'')+'" data-theme="'+t.key+'"><b>'+esc(t.name)+'</b><div class="swatches"><i class="swatch" style="background:'+t.p+'"></i><i class="swatch" style="background:'+t.a+'"></i><i class="swatch" style="background:'+t.bg+'"></i><i class="swatch" style="background:'+t.text+'"></i></div></button>').join('')+'</div><div class="sectionbox" style="margin-top:16px"><h3>Custom palette</h3><form id="customTheme" class="formgrid"><div class="field"><label>Primary</label><input type="color" name="primary" value="'+esc(s.custom_theme?.primary||'#4B2E92')+'"></div><div class="field"><label>Accent</label><input type="color" name="accent" value="'+esc(s.custom_theme?.accent||'#C9B8F5')+'"></div><div class="field"><label>Background</label><input type="color" name="background" value="'+esc(s.custom_theme?.background||'#F5F2FC')+'"></div><div class="field"><label>Text</label><input type="color" name="text" value="'+esc(s.custom_theme?.text||'#1A1730')+'"></div><div class="field full"><button class="btn">Apply custom palette</button><small>Custom colors are only activated after you confirm this action.</small></div></form></div>';
  backGeneral.onclick=generalView;
  themeGrid.querySelectorAll('[data-theme]').forEach(b=>b.onclick=async()=>{const key=b.dataset.theme;if(key==='custom')return customTheme.scrollIntoView({behavior:'smooth'});const label=b.querySelector('b')?.textContent||'this theme';if(!confirm('Apply '+label+' to the public website?'))return;const {error}=await sb.from('site_settings').update({theme_key:key}).eq('id',1);if(error)return toast(error.message);sessionStorage.removeItem('nexus_site_bundle_v3');alert('Theme changed successfully.');appearanceView()});
  customTheme.onsubmit=async e=>{e.preventDefault();if(!confirm('Apply this custom palette to the public website?'))return;const p=Object.fromEntries(new FormData(customTheme));const {error}=await sb.from('site_settings').update({theme_key:'custom',custom_theme:p}).eq('id',1);if(error)return toast(error.message);sessionStorage.removeItem('nexus_site_bundle_v3');alert('Custom palette applied successfully.');appearanceView()}
}
async function announcementsView(){
  const {data:items=[],error}=await sb.from('announcements').select('*').order('priority',{ascending:false}).order('created_at',{ascending:false});if(error)return panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Pop-ups & banners</h2><p>Create event prompts, holiday notices and calls to action.</p></div><button class="btn" id="newAnn">New pop-up</button></div><div class="tablewrap"><table><thead><tr><th>Title</th><th>Type</th><th>Schedule</th><th>Status</th><th></th></tr></thead><tbody>'+items.map(x=>'<tr><td class="wrap"><b>'+esc(x.title)+'</b><div class="muted">'+esc(x.body||'')+'</div></td><td>'+esc(x.display_type||'popup')+'</td><td>'+esc(x.starts_at?fmt(x.starts_at):'Now')+' → '+esc(x.ends_at?fmt(x.ends_at):'No end')+'</td><td><span class="status '+(x.published?'published':'draft')+'">'+(x.published?'Published':'Draft')+'</span></td><td><button class="btn small secondary" data-edit="'+x.id+'">Edit</button></td></tr>').join('')+'</tbody></table></div>';
  panel.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>announcementEditor(items.find(x=>x.id===b.dataset.edit)));newAnn.onclick=()=>announcementEditor({display_type:'popup',dismissible:true})
}
function announcementEditor(x){
  panel.innerHTML='<div class="toolbar"><h2>'+(x.id?'Edit pop-up':'New pop-up')+'</h2><button class="btn secondary" id="backAnn">Back</button></div><form id="annForm" class="formgrid"><div class="field"><label>Title</label><input name="title" value="'+esc(x.title||'')+'" required></div><div class="field"><label>Display</label><select name="display_type"><option value="popup" '+(x.display_type!=='banner'?'selected':'')+'>Small pop-up</option><option value="banner" '+(x.display_type==='banner'?'selected':'')+'>Top banner</option></select></div><div class="field full"><label>Message</label><textarea name="body">'+esc(x.body||'')+'</textarea></div><div class="field"><label>Button label</label><input name="cta_label" value="'+esc(x.cta_label||'Register')+'"></div><div class="field"><label>Button URL</label><input name="link_url" value="'+esc(x.link_url||'/events')+'"></div><div class="field"><label>Start</label><input type="datetime-local" name="starts_at" value="'+(x.starts_at?new Date(x.starts_at).toISOString().slice(0,16):'')+'"></div><div class="field"><label>End</label><input type="datetime-local" name="ends_at" value="'+(x.ends_at?new Date(x.ends_at).toISOString().slice(0,16):'')+'"></div><div class="field"><label>Priority</label><input type="number" name="priority" value="'+esc(x.priority??0)+'"></div><div class="field"><label><input type="checkbox" name="dismissible" '+(x.dismissible!==false?'checked':'')+'> Dismissible</label></div><div class="field full"><div class="publishbox"><b>Public visibility</b><label><input type="checkbox" name="published" '+(x.published?'checked':'')+'> Published</label></div></div><div class="field full"><button class="btn">Save pop-up</button></div></form>';
  backAnn.onclick=announcementsView;annForm.onsubmit=async e=>{e.preventDefault();const f=new FormData(annForm),payload={title:f.get('title').trim(),body:f.get('body').trim(),display_type:f.get('display_type'),cta_label:f.get('cta_label').trim(),link_url:f.get('link_url').trim(),starts_at:f.get('starts_at')?new Date(f.get('starts_at')).toISOString():null,ends_at:f.get('ends_at')?new Date(f.get('ends_at')).toISOString():null,priority:Number(f.get('priority')||0),dismissible:annForm.dismissible.checked,published:annForm.published.checked,published_at:annForm.published.checked?(x.published_at||new Date().toISOString()):null};const cmd=x.id?sb.from('announcements').update(payload).eq('id',x.id):sb.from('announcements').insert(payload);const {error}=await cmd;if(error)return toast(error.message);toast('Pop-up saved.');announcementsView()}
}
async function messagesView(){
  const {data:items=[],error}=await sb.from('contact_messages').select('*').order('created_at',{ascending:false});if(error)return panel.innerHTML='<div class="empty">'+esc(error.message)+'</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Contact messages</h2><p>Messages submitted from the public Contact page.</p></div><button class="btn secondary" id="exportMessages">Export CSV</button></div><div class="tablewrap"><table><thead><tr><th>From</th><th>Subject</th><th>Message</th><th>Received</th><th></th></tr></thead><tbody>'+items.map(x=>'<tr><td>'+esc(x.full_name)+'<br><span class="muted">'+esc(x.email)+'</span></td><td>'+esc(x.subject||'—')+'</td><td class="wrap">'+esc(x.message)+'</td><td>'+esc(fmt(x.created_at))+'</td><td>'+(currentRole==='owner'?'<button class="btn small danger" data-del-message="'+x.id+'">Delete</button>':'')+'</td></tr>').join('')+'</tbody></table></div>';exportMessages.onclick=()=>downloadCsv(items,'nexus-contact-messages.csv',['full_name','email','subject','message','created_at']);panel.querySelectorAll('[data-del-message]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this contact message?'))return;const {error}=await sb.from('contact_messages').delete().eq('id',b.dataset.delMessage);if(error)return toast(error.message);messagesView()})
}
async function teamApi(body){const {data,error}=await sb.functions.invoke('admin-team',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data||{}}
async function teamView(){
  if(currentRole!=='owner')return panel.innerHTML='<div class="empty">Owner authorization required.</div>';
  panel.innerHTML='<div class="toolbar"><div><h2>Team Access</h2><p>Invite collaborators while keeping publishing and destructive actions under owner control.</p></div><button class="btn" id="inviteTeam">Invite member</button></div><div class="notice"><b>Approval model:</b> team members can prepare drafts, upload media, edit forms/pages and view submissions. Owner-only permissions remain enforced by database policies for publishing/deletion/application decisions where configured.</div><div id="teamPane"><div class="empty">Loading…</div></div>';
  async function load(){try{const {members=[]}=await teamApi({action:'list'});teamPane.innerHTML='<div class="tablewrap"><table><thead><tr><th>Person</th><th>Role</th><th>Status</th><th>Invited</th><th></th></tr></thead><tbody>'+members.map(m=>'<tr><td><b>'+esc(m.display_name||m.email||'Team member')+'</b><div class="muted">'+esc(m.email||'')+'</div></td><td>'+esc(m.role==='owner'?'Owner':'Team member')+'</td><td><span class="status '+(m.active?'active':'disabled')+'">'+(m.active?'Active':'Disabled')+'</span></td><td>'+esc(fmt(m.invited_at||m.created_at))+'</td><td>'+(m.role==='owner'?'Protected owner':'<button class="btn small secondary" data-id="'+m.user_id+'" data-active="'+(!m.active)+'">'+(m.active?'Disable':'Restore')+'</button>')+'</td></tr>').join('')+'</tbody></table></div>';teamPane.querySelectorAll('[data-id]').forEach(b=>b.onclick=async()=>{try{await teamApi({action:'set_active',user_id:b.dataset.id,active:b.dataset.active==='true'});toast('Access updated.');load()}catch(e){toast(e.message)}})}catch(e){teamPane.innerHTML='<div class="empty">'+esc(e.message)+'</div>'}}load();
  inviteTeam.onclick=()=>{teamPane.innerHTML='<div class="card" style="padding:18px"><h3>Invite team member</h3><form id="inviteForm" class="formgrid"><div class="field"><label>Name</label><input name="display_name"></div><div class="field"><label>Email</label><input type="email" name="email" required></div><div class="field full"><button id="sendInvite" class="btn">Send invitation</button></div></form></div>';inviteForm.onsubmit=async e=>{e.preventDefault();busy(sendInvite,true,'Sending…');const f=new FormData(inviteForm);try{await teamApi({action:'invite',email:f.get('email').trim(),display_name:f.get('display_name').trim(),site_url:location.origin});toast('Invitation sent.');load()}catch(err){busy(sendInvite,false,'Send invitation');toast(err.message)}}}
}
boot();
